### ISSUE TITLE
Fatal on wordpress 4.4

### ISSUE THREAD

**Issue by fffonion** [aramk/crayon-syntax-highlighter#320]
Stacktrace is 
```
Fatal error: Uncaught Error: Call to undefined method CrayonUtil::lines() in /home/www/blog/wp-content/plugins/aramk-crayon-syntax-highlighter-a223038/crayon_parser.class.php:55
Stack trace: #0 /home/www/blog/wp-content/plugins/aramk-crayon-syntax-highlighter-a223038/crayon_langs.class.php(76): CrayonParser::parse('default')
#1 /home/www/blog/wp-content/plugins/aramk-crayon-syntax-highlighter-a223038/crayon_resource.class.php(119): CrayonLangs->add_default()
#2 /home/www/blog/wp-content/plugins/aramk-crayon-syntax-highlighter-a223038/crayon_langs.class.php(55): CrayonResourceCollection->load_process()
#3 /home/www/blog/wp-content/plugins/aramk-crayon-syntax-highlighter-a223038/crayon_resource.class.php(74): CrayonLangs->load_process()
#4 /home/www/blog/wp-content/plugins/aramk-crayon-syntax-highlighter-a223038/crayon_settings_wp.class.php(273): CrayonResourceCollection->load()
#5 /home/www/blog/wp-content/plugins/aramk-crayon-syntax-highlighter-a223038/crayon_wp.class.php(562): CrayonSettingsWP::load_settings()
#6 /home/w in /home/www/blog/wp-content/plugins/aramk-crayon-syntax-highlighter-a223038/crayon_parser.class.php on line 55
```

Environment is PHP7.0 on Ubuntu 14.04.3 32bit
Works fine for me before wordpress 4.4

tested both stable version and beta version

**Comment by fffonion** [comment]
Looks like a expired cache in php opcache. Not a plugin bug ;-)
