### ISSUE TITLE
Fatal error after editing theme

### ISSUE THREAD

**Issue by Luggruff** [aramk/crayon-syntax-highlighter#437]
I tried naming my theme "1" and used parenthesis in the Author field. The settings page crashed with the error code below, and I cannot find either the theme with the original name (duplicated theme name) or with the new name I tried giving it anywhere on my FTP. 

I have no idea how to fix this, but need a fix asap.

Fatal error: Uncaught Error: Call to a member function user() on null in /home/s4nmneq4j1f2/public_html/blog/wp-content/plugins/crayon-syntax-highlighter/crayon_settings_wp.class.php:981 Stack trace: #0 /home/s4nmneq4j1f2/public_html/blog/wp-admin/includes/template.php(1378): CrayonSettingsWP::theme(Array) #1 /home/s4nmneq4j1f2/public_html/blog/wp-admin/includes/template.php(1337): do_settings_fields('crayon_fields', 'crayon_general') #2 /home/s4nmneq4j1f2/public_html/blog/wp-content/plugins/crayon-syntax-highlighter/crayon_settings_wp.class.php(220): do_settings_sections('crayon_fields') #3 /home/s4nmneq4j1f2/public_html/blog/wp-includes/class-wp-hook.php(286): CrayonSettingsWP::settings('') #4 /home/s4nmneq4j1f2/public_html/blog/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters('', Array) #5 /home/s4nmneq4j1f2/public_html/blog/wp-includes/plugin.php(453): WP_Hook->do_action(Array) #6 /home/s4nmneq4j1f2/public_html/blog/wp-admin/admin.php(224): do_action('settings_page_c...') #7 /home/s4nmneq4j1f2/public_html/bl in **/home/s4nmneq4j1f2/public_html/blog/wp-content/plugins/crayon-syntax-highlighter/crayon_settings_wp.class.php** on line **981**

**Comment by Luggruff** [comment]
Nevermind. I had to start all over again, but it finally worked when I deleted this folder:
wp-content/uploads/crayon-syntax-highlighter/themes/1
