### ISSUE TITLE
The plug-in breaks the website when the plug-in is deactivated, it just starts to work

### ISSUE THREAD

**Issue by JayantVarma** [aramk/crayon-syntax-highlighter#476]
```[27-May-2020 01:34:05 UTC] PHP Warning:  preg_replace(): Compilation failed: invalid range in character class at offset 4 in /my/domain/location/site/wp-content/plugins/crayon-syntax-highlighter/crayon_langs.class.php on line 340
[27-May-2020 01:34:05 UTC] PHP Fatal error:  Uncaught Error: Call to a member function id() on array in /my/domain/location/site/wp-content/plugins/crayon-syntax-highlighter/crayon_formatter.class.php:36
Stack trace:
#0 /my/domain/location/site/wp-content/plugins/crayon-syntax-highlighter/crayon_formatter.class.php(538): CrayonFormatter::format_code('', Array, Object(CrayonHighlighter))
#1 [internal function]: CrayonFormatter::delim_to_internal(Array)
#2 /my/domain/location/site/wp-content/plugins/crayon-syntax-highlighter/crayon_formatter.class.php(516): preg_replace_callback('#()#msi', 'CrayonFormatter...', 'print("message"...')
#3 /my/domain/location/site/wp-content/plugins/crayon-syntax-highlighter/crayon_highlighter.class.php(166): CrayonFormatter::format_mixed_code('print("message"...', Object(CrayonLang), Object(CrayonHighlighter))
#4 /my/domain/location/site/wp-content/plugins/crayon-syntax-highlighter/crayon_highlighter.class.php(186): CrayonHighlighter->process()
#5 /my/domain/location/site/wp-co in /my/domain/location/site/wp-content/plugins/crayon-syntax-highlighter/crayon_formatter.class.php on line 36```

**Comment by worldsdream** [comment]
Please use the following plugin. It’s a fork of crayon syntax highligther. 

I have been using it for a while and I don’t have issues. 

If you do have problems, let the developer know on the support page of the plugin. 

https://wordpress.org/plugins/urvanov-syntax-highlighter/
